### ISSUE TITLE
Command line string to set a default audio device

### ISSUE THREAD

**Issue by LLBlumire** [TheEpicSnowWolf/TheEpicAudioStreamer#1]
I'd like to be able to start this up without doing any command line inputs after starting the program, as such something like

`teas.exe -p <prefix> -t <token> -d 1`

or

`teas.exe -p <prefix> -t <token> -n "Speakers (High Definition Audio Device)"`

for `-d` device number or `-n` device name?

**Comment by TheEpicSnowWolf** [comment]
Sorry for the late reply, I think that's a great suggestion! I will get to it as soon as possible.

**Comment by TheEpicSnowWolf** [comment]
@LLBlumire This feature is now available in [version 0.3.0](https://github.com/TheEpicSnowWolf/TheEpicAudioStreamer/releases/tag/v0.3.0). Thanks again for the suggestion!

I decided to not use the device number, as that number can change depending on the currently available audio devices. Instead, the new argument accepts a "friendly device name", that is the name in brackets in the devices list, for example `High Definition Audio Device`. This name should be unique on the user's configuration.

Let me know if you run into any issues with this.
