### ISSUE TITLE
Bot Owner instead of Server Manager

### ISSUE THREAD

**Issue by LLBlumire** [TheEpicSnowWolf/TheEpicAudioStreamer#2]
Would it be possible to add an option to start the bot such that it listens to you as a bot owner, even if you are not a server manager? If you've persuaded the managers of a server to add your bot to the server in the first place then likely it is expected that you as the owner can control it, even if you do not manage the server.

**Comment by TheEpicSnowWolf** [comment]
I'm currently looking into this. Unfortunately, I don't think it's possible to retrieve who the owner of a bot account is, but there might be a workaround solution with which you could specify a user via command line argument whose commands the bot then also accepts.

**Comment by TheEpicSnowWolf** [comment]
[Version 0.4.0](https://github.com/TheEpicSnowWolf/TheEpicAudioStreamer/releases/tag/v0.4.0) now has a command line option to specify an 'admin' user, i.e. a user that the bot accepts commands from in addition to the server managers. I have limited means to test this in the wild, so please feel free to open a new issue here in case any problems occur.

**Comment by JoqniX** [comment]
hi is it possible to tie this under a role too? like how other music bots has a dj role? or so?

**Comment by dandln** [comment]
See linked issue above
